# Generated by Django 6.0.2 on 2026-09-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_equipmenthistory_date_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('serviced', 'Serviced'), ('request', 'Request'), ('moved', 'Moved')], max_length=20),
        ),
    ]
